apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: train-pipeline
  annotations:
    scenarios.ai.sap.com/description: "Tutorial to add custom code to SAP AI Core"
    scenarios.ai.sap.com/name: "Train Flight Price Predictor"
    executables.ai.sap.com/description: "Trains model on preedicting flight prices"
    executables.ai.sap.com/name: "Flight Price (Sklearn Example)"
    artifacts.ai.sap.com/flightdataset.kind: "dataset" # Helps in suggesting the kind of inputs that can be attached.
  labels:
    scenarios.ai.sap.com/id: "train-code"
    ai.sap.com/version: "1.0"
spec:
  imagePullSecrets:
    - name: credstutorialrepo # your docker registry secret
  entrypoint: mypipeline
  templates:
  - name: mypipeline
    steps:
    - - name: mypredictor
        template: mycodeblock1

  - name: mycodeblock1
    inputs:
      artifacts: 
        - name: flightdataset 
          path: /app/data/ 
    outputs:
      artifacts:
        - name: flightpricemodel
          globalName: flightmodel 
          path: /app/model/
          archive:
            none:  
              {}
    container:
      image: docker.io/noravth/flight-price:01 
      command: ["/bin/sh", "-c"]
      args:
        - "python /app/src/main.py"
